# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: windows-latest
    env: 
      username : ${{ secrets.usr_name}}
      password : ${{ secrets.psd}}
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19.0.1'
        distribution: 'temurin'
        
    - name: build with maven
      run: mvn clean install
      
   # - name: Start Selenium Grid
   #   run: |
    #      wget -q -O selenium-server-standalone.jar https://selenium-release.storage.googleapis.com/3.141/selenium-server-standalone-3.141.59.jar
   #       java -jar selenium-server-standalone.jar -role hub &

    - name: Run Selenium tests
      run: mvn test
